import React, { useState } from 'react';
import { Code2, Play, Bug, FileCode, CheckCircle2, Terminal, GitBranch, RefreshCw, Flame } from 'lucide-react';
import { soundEffects } from '../services/soundEffects';

export const CodingView: React.FC = () => {
  const [activeFile, setActiveFile] = useState('calculator.py');
  const [isRunning, setIsRunning] = useState(false);
  const [output, setOutput] = useState<string>(
    '[STARK OS Python Runtime: Python 3.11.8 on Windows 11]\n> Target: C:\\Users\\User\\Projects\\PythonCalculator\\calculator.py\n> System: Intel Core i5 / RTX 4050\n> Ready for autonomous compilation and verification...'
  );

  const files: Record<string, string> = {
    'calculator.py': `"""
Python Scientific Calculator Module
Authored by J.A.R.V.I.S. Desktop Coding Agent
"""
import math

class Calculator:
    def add(self, a: float, b: float) -> float:
        return a + b

    def subtract(self, a: float, b: float) -> float:
        return a - b

    def multiply(self, a: float, b: float) -> float:
        return a * b

    def divide(self, a: float, b: float) -> float:
        if b == 0:
            raise ValueError("ZeroDivisionError: Cannot divide by zero.")
        return a / b

    def power(self, base: float, exp: float) -> float:
        return math.pow(base, exp)

    def sqrt(self, n: float) -> float:
        if n < 0:
            raise ValueError("DomainError: Cannot take square root of negative number.")
        return math.sqrt(n)

if __name__ == "__main__":
    calc = Calculator()
    print("[J.A.R.V.I.S.] Self-testing calculator routines...")
    print("  5 * 8 =", calc.multiply(5, 8))
    print("  sqrt(144) =", calc.sqrt(144))
    print("  2 ** 10 =", calc.power(2, 10))
    print("[Verification] All 6 calculator unit assertions passed successfully.")
`,
    'app.py': `"""
J.A.R.V.I.S. Local Assistant Orchestrator Bridge
Target: Windows 11 Desktop
"""
import sys
import os

def main():
    print("[STARK Kernel] Initializing Windows 11 bridge...")
    print("[STARK Kernel] Connected to Ollama qwen3:8b and Gemini models.")
    print("[STARK Kernel] Hardware: Intel i5-13500H + NVIDIA RTX 4050.")
    print("[STARK Kernel] Status: 38 tools ready for autonomous execution.")

if __name__ == "__main__":
    main()
`,
    'prime_check.c': `/*
 * C Number Theory Module: Prime Verification
 * Generated by J.A.R.V.I.S. Coding Agent
 */
#include <stdio.h>
#include <stdbool.h>
#include <math.h>

bool is_prime(long long n) {
    if (n <= 1) return false;
    if (n <= 3) return true;
    if (n % 2 == 0 || n % 3 == 0) return false;
    for (long long i = 5; i * i <= n; i += 6) {
        if (n % i == 0 || n % (i + 2) == 0) return false;
    }
    return true;
}

int main() {
    long long test_num = 1000000007; // Prime
    printf("[STARK C Engine] Testing %lld is prime: %s\\n", 
           test_num, is_prime(test_num) ? "TRUE (PRIME)" : "FALSE");
    return 0;
}
`,
  };

  const handleRunCode = () => {
    soundEffects.playReactorPulse();
    setIsRunning(true);
    setOutput(`[STARK Windows 11 Shell] Compiling & launching ${activeFile}...\n`);

    setTimeout(() => {
      if (activeFile === 'calculator.py') {
        setOutput(
          `[STARK Python Runtime: Python 3.11.8 on Windows 11]\n` +
          `> python C:\\Users\\User\\Projects\\PythonCalculator\\calculator.py\n` +
          `[J.A.R.V.I.S.] Self-testing calculator routines...\n` +
          `  5 * 8 = 40.0\n` +
          `  sqrt(144) = 12.0\n` +
          `  2 ** 10 = 1024.0\n` +
          `[Verification] All 6 calculator unit assertions passed successfully.\n` +
          `[Process terminated with exit code 0 in 38ms]\n` +
          `✓ VERIFIED: Script runs with zero syntax or runtime errors.`
        );
      } else if (activeFile === 'app.py') {
        setOutput(
          `[STARK Python Runtime]\n` +
          `> python app.py\n` +
          `[STARK Kernel] Initializing Windows 11 bridge...\n` +
          `[STARK Kernel] Connected to Ollama qwen3:8b and Gemini models.\n` +
          `[STARK Kernel] Hardware: Intel i5-13500H + NVIDIA RTX 4050.\n` +
          `[STARK Kernel] Status: 38 tools ready for autonomous execution.\n` +
          `[Process terminated with exit code 0 in 42ms]`
        );
      } else {
        setOutput(
          `[STARK C/C++ GCC Compiler]\n` +
          `> gcc prime_check.c -o prime_check.exe -O3\n` +
          `> .\\prime_check.exe\n` +
          `[STARK C Engine] Testing 1000000007 is prime: TRUE (PRIME)\n` +
          `[Build & execution succeeded in 84ms]`
        );
      }
      setIsRunning(false);
    }, 600);
  };

  const handleRunAgenticLoop = () => {
    soundEffects.playClick();
    setIsRunning(true);
    setOutput(
      `[J.A.R.V.I.S. Autonomous Agentic Loop: 7-Step Pipeline Engaged]\n` +
      `Step 1: Inspecting project syntax tree & imports... ✓\n` +
      `Step 2: Checking type hints and boundary conditions... ✓\n` +
      `Step 3: Running compiler verification (py_compile)... ✓\n` +
      `Step 4: Synthesizing unit test suite (test_calculator.py)... ✓\n` +
      `Step 5: Executing unit test suite with coverage analysis... ✓\n` +
      `Step 6: Confirming clean exit code (0)... ✓\n` +
      `Step 7: Final Report: Codebase verified. Zero errors detected.\n`
    );
    setIsRunning(false);
  };

  return (
    <div id="jarvis-coding-view" className="flex-1 h-full overflow-hidden p-4 sm:p-6 flex flex-col font-['Michroma',sans-serif] text-xs bg-[#050203] text-white">
      {/* Top Header */}
      <div className="flex items-center justify-between border-b-2 border-[#880015] pb-4 mb-4">
        <div className="flex items-center gap-3">
          <Code2 className="w-5 h-5 text-[#ff0033]" />
          <div>
            <h2 className="text-sm font-bold text-white tracking-widest uppercase drop-shadow-[0_0_8px_rgba(255,255,255,0.6)]">
              AUTONOMOUS CODING AGENT WORKSPACE
            </h2>
            <div className="text-[10px] text-[#ffd700] tracking-wider mt-0.5">
              PYTHON 3.11 • GCC C/C++ • POWERSHELL • STARK MATRIX
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={handleRunAgenticLoop}
            className="px-3 py-1.5 rounded-sm border border-[#880015] bg-[#0a0204] hover:bg-[#880015]/30 hover:border-[#ffd700] text-white flex items-center gap-1.5 transition-all text-[10px] tracking-wider cursor-pointer"
          >
            <RefreshCw className="w-3.5 h-3.5 text-[#ffd700]" />
            <span>AGENTIC AUDIT &amp; FIX</span>
          </button>
          <button
            type="button"
            onClick={handleRunCode}
            disabled={isRunning}
            className="px-4 py-1.5 rounded-sm bg-gradient-to-r from-[#ff0033] to-[#ffd700] hover:opacity-90 text-black font-bold flex items-center gap-1.5 transition-all shadow-[0_0_12px_rgba(255,0,51,0.5)] text-[10px] tracking-wider cursor-pointer"
          >
            <Play className="w-3.5 h-3.5" />
            <span>{isRunning ? 'RUNNING...' : 'RUN FILE'}</span>
          </button>
        </div>
      </div>

      {/* Main Coding Layout */}
      <div className="flex-1 flex flex-col lg:flex-row gap-4 overflow-hidden">
        {/* Left: Project File Tree */}
        <div className="w-full lg:w-60 rounded-sm border border-[#880015]/70 bg-[#0a0204]/90 p-3 flex flex-col gap-2 shadow-xl">
          <div className="flex items-center justify-between text-[10px] text-white/70 uppercase tracking-wider pb-2 border-b border-[#880015]/50">
            <span className="flex items-center gap-1.5 font-bold">
              <GitBranch className="w-3.5 h-3.5 text-[#ff0033]" />
              <span>PROJECT FILES</span>
            </span>
            <span className="text-[9px] text-[#ffd700]">main*</span>
          </div>

          <div className="flex-1 space-y-1 overflow-y-auto pt-1">
            {Object.keys(files).map((fileName) => (
              <button
                key={fileName}
                type="button"
                onClick={() => { soundEffects.playClick(); setActiveFile(fileName); }}
                className={`w-full p-2 rounded-sm flex items-center gap-2 text-left transition-all cursor-pointer ${
                  activeFile === fileName
                    ? 'border border-[#ff0033] bg-[#880015]/40 text-white font-bold shadow-[0_0_8px_rgba(255,0,51,0.4)]'
                    : 'text-white/70 hover:bg-[#880015]/20 hover:text-white'
                }`}
              >
                <FileCode className="w-4 h-4 text-[#ffd700] shrink-0" />
                <span className="truncate font-mono text-[11px]">{fileName}</span>
              </button>
            ))}
          </div>

          <div className="p-2 rounded-sm border border-[#880015]/40 bg-black/60 text-[9px] text-white/70 space-y-0.5">
            <div>Target: Windows 11</div>
            <div className="text-[#ffd700]">Runtime: Local Python / C</div>
          </div>
        </div>

        {/* Center: Code View & Editor */}
        <div className="flex-1 flex flex-col rounded-sm border border-[#880015]/70 bg-[#0a0204]/90 overflow-hidden shadow-xl">
          <div className="p-2.5 px-4 border-b border-[#880015]/70 bg-black/60 flex items-center justify-between text-xs">
            <span className="font-bold text-white font-mono">{activeFile}</span>
            <span className="text-[#ffd700] text-[9px] tracking-wider">UTF-8 • LF • STARK CODE ENGINE</span>
          </div>
          <div className="flex-1 p-4 overflow-y-auto bg-black/90 text-white/90 font-mono text-[12px] leading-relaxed select-text">
            <pre className="whitespace-pre">{files[activeFile] || '# File empty'}</pre>
          </div>
        </div>

        {/* Right: Terminal Console Output */}
        <div className="w-full lg:w-80 rounded-sm border border-[#880015]/70 bg-[#070204]/95 flex flex-col overflow-hidden shadow-xl">
          <div className="p-2.5 px-3 border-b border-[#880015]/70 bg-black/60 flex items-center justify-between text-xs">
            <span className="flex items-center gap-1.5 font-bold text-white">
              <Terminal className="w-3.5 h-3.5 text-[#ff0033]" />
              <span className="tracking-wider">TERMINAL OUTPUT</span>
            </span>
            <span className="text-[9px] text-[#ffd700]">STDOUT / STDERR</span>
          </div>
          <div className="flex-1 p-3 overflow-y-auto text-[11px] font-mono text-white/90 whitespace-pre-wrap leading-relaxed select-text bg-black/50">
            {output}
          </div>
        </div>
      </div>
    </div>
  );
};
